wandb_version: 1

BATCH_SIZES:
  desc: null
  value:
  - 256
  - 256
  - 128
  - 64
  - 32
  - 16
  - 8
  - 4
EPOCHS:
  desc: null
  value:
  - 20
  - 30
  - 40
  - 50
  - 60
  - 70
  - 80
LAMBDA_GP:
  desc: null
  value: 10
W_DIM:
  desc: null
  value: 512
Z_DIM:
  desc: null
  value: 512
_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.10.6
    start_time: 1674450536.63799
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 17
      - 23
      - 37
      4: 3.10.6
      5: 0.13.7
      8:
      - 5
      10:
      - 3
